name: BuildDartLib
on:
  workflow_dispatch:
    inputs:
      push-branch:
        description: "Push Branch"
        required: true
        default: 'build-dart-lib'
      patch-rep:
        description: "Patch File Repository"
        required: true
        default: 'https://github.com/Hakdaw/Darting.git'
      patch-branch:
        description: "Patch File Branch"
        required: true
        default: 'work-patch'

jobs:
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Clone Dart
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export PATH="$PATH:$PWD/depot_tools"
          mkdir dart_sdk
          cd dart_sdk
          fetch dart
          gclient sync

      - name: Clone Patch
        run: |
          git clone -b ${{ github.event.inputs.patch-branch }} ${{github.event.inputs.patch-rep}}
          cp -f ./Darting/BUILD.gn ./dart_sdk/sdk/
          cp -f ./Darting/runtime/BUILD.gn ./dart_sdk/sdk/runtime/bin/

      - name: Build Dart Lib
        run: |
          cd dart_sdk/sdk
          python ./tools/build.py --no-goma -m release libdart
      
      - name: Commit
        run: |
          cd dart_sdk/sdk/out/
          git add .
          git commit -m "Actions Autogen:`date`"
          git pull

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          branch: ${{ github.event.inputs.push-branch }}
          