name: GenDartSDK

on:
    workflow_dispatch:
        inputs:
            branch:
                description: "Push Branch"
                required: true
                default: 'gen-dart'

jobs: 
    Gen:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: '3.8'

            - name: Clone Dart
              run: |
                git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
                export PATH="$PATH:$PWD/depot_tools"
                mkdir dart_sdk
                cd dart_sdk
                fetch dart
                gclient sync

            - name: Commit
              run: |
                git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
                cd dart_sdk/sdk
                rm -rf ".git"
                cd ../../
                git add .
                git commit -m "Actions Autogen:`date`"
                git remote set-url ${{ github.event.inputs.branch }} https://${{ github.actor }}:${{ secrets.PUSH_TOKEN }}@github.com/${{ github.repository }}
                git push